todo_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls'))
]

todoapp/urls.py
from django.urls import path
from . import views

app_name = 'todoapp'

urlpatterns = [
	# Home page
	path('todoapp/', views.todoappView, name='todoappView'),
    path('addTodoItem/', views.addTodoItem, name='addTodoItem'),
    path('deleteTodoItem/<int:i>/', views.deleteTodoItem, name='deleteTodoItem'),
]

todoapp/models.py
from django.db import models

class TodoListItem(models.Model):
    content = models.TextField()

    def __str__(self):
        """Return a string representation of the model."""
        return self.content

todoapp/views.py
from django.shortcuts import render, redirect
from .models import TodoListItem

def todoappView(request):
    """The home page for the Todo List App."""
    all_todo_items = TodoListItem.objects.all()
    context = { 'all_items' : all_todo_items }
    return render(request, 'todoapp/todo_list.html', context)

def addTodoItem(request):
    x = request.POST['content']
    new_item = TodoListItem(content = x)
    new_item.save()
    return redirect('todoapp:todoappView')

def deleteTodoItem(request, i):
    y = TodoListItem.objects.get(id=i)
    y.delete()
    return redirect('todoapp:todoappView')

todoapp/templates/todoapp/todo_list.html
<h1>My To Do List</h1>
<form method="post" action="{% url 'todoapp:addTodoItem' %}">
  {% csrf_token %}
  <input type="text" name="content">
  <input type="submit" value="Add Todo Item">
</form>
<ul>
    {% for i in all_items %}
    <li>
      <h4>{{i.content}}<small><form method="post" action="{% url 'todoapp:deleteTodoItem' i.id %}">
        {% csrf_token %}
        <input type="submit" value="Delete"></small></form>
      </h4>
    </li>
    {% endfor %}
</ul>